# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbfcc8a3caafbfa6155bd7318f8c6d5f8ccbe7915418b42acf44860cc73927c4532d2af84e282bb866f32619c9aee30ba3d0e12297e9614dbabb629bd6ee91c8

test:
  secret_key_base: f7fc7ceabdce054b0b51d47dd464fd03f9c35dfe2e1b1ecbb2dc715a177fbd472f20a332448b8472906121e7d2c8f6504156a1d07d6bcd25555a76f00e542cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
